name: Python Pull Request Action
on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Run Python script on pull request to main
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11' # Replace 'x' with the appropriate Python version you need
        
    - name: Run Python script
      run: python3 switchConfig.py dev_config.json prod_config.json # Replace "main.py" with the name of your Python script
